apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: single-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  description: Applications for one Kubernetes cluster managed from this GitOps repository.
  sourceRepos:
    - https://github.com/catdevdev/gitops-template-argocd.git
    - https://charts.jetstack.io
    - https://charts.external-secrets.io
    - https://kubernetes-sigs.github.io/external-dns/
    - https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    - https://stefanprodan.github.io/podinfo
    - https://charts.bitnami.com/bitnami
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
