apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: single-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  description: Applications for one Kubernetes cluster managed from this GitOps repository.
  sourceRepos:
    - https://github.com/catdevdev/gitops-template-argocd.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
