apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - projects/single-cluster-project.yaml
  - applicationsets/platform-controllers.yaml
  - applicationsets/platform-configs.yaml
  - applicationsets/platform-addons.yaml
  - applicationsets/workload-apps.yaml
