apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-controllers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/catdevdev/gitops-template-argocd.git
        revision: main
        files:
          - path: platform-apps/controllers/*.yaml
  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: single-cluster
        gitops.layer: platform-controllers
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: single-cluster
      source:
        repoURL: "{{.repoURL}}"
        chart: "{{.chart}}"
        targetRevision: "{{.targetRevision}}"
        helm:
          releaseName: "{{.releaseName}}"
          values: "{{.values}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
